[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "netsip"
version = "1.0.0"

description = "Python SDK for NetSIPCore SIP engine"

readme = "README.md"

license = {file = "LICENSE"}

requires-python = ">=3.10"

authors = [
    {name = "WildRogerr"}
]


classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)"
]


dependencies = []


[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.package-data]
netsip = [
    "NetSIPCore.exe",
    "NetSIPCore",
    "resources/*.wav"
]